email_smtp_host: localhost
email_smtp_port: 587
email_from: noreply@localhost
email_reply_to: "{{ email_from }}"
email_username: "email_user"
email_password: "email_password"

config_entry_list:
  - usersbl_reset.json.j2

email_entry_list:
  - email_config.json.j2

okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
stripes_url: "http://{{ ansible_default_ipv4.address }}"

tenant: diku
admin_user:
  username: diku_admin
  password: admin

# Set to 'True' to enable suppression of user edits
do_suppress_edit: False

# If 'do-suppress-edit' is set, suppress edit of tenant admin by default
suppress_edit_userlist:
  - "{{ admin_user.username }}"

