---

- name: Create configuration source directory
  become: yes
  file:
    path: '/etc/folio/okapi'
    state: directory

- name: Install okapi.json
  become: yes
  template:
    src: okapi.json.j2
    dest: /etc/folio/okapi/okapi.json
    mode: 0600
    backup: yes
  
- name: Create and Launch Okapi Docker Container
  become: yes
  docker_container:
    name: okapi
    image: "{{ okapi_image }}"
    volumes:
      - /etc/folio/okapi/okapi.json:/etc/folio/okapi/okapi.json
    ports:
      - "{{ okapi_port }}:9130"
    state: started
    restart_policy: always
    command: "dev -conf /etc/folio/okapi/okapi.json"
    restart: yes
  

  
