---

- name: Create configuration source directory
  become: yes
  file:
    path: '/etc/folio/okapi'
    state: directory

# Need to set group to 1000 for file to be readable by user in Okapi
# container
- name: Install okapi.json
  become: yes
  template:
    src: okapi.json.j2
    dest: /etc/folio/okapi/okapi.json
    group: 1000
    mode: 0640
    backup: yes

- name: Create and Launch Okapi Docker Container
  become: yes
  docker_container:
    name: okapi
    image: "{{ okapi_image }}"
    volumes:
      - /etc/folio/okapi:/usr/verticles/okapi:ro
    ports:
      - "{{ okapi_port }}:9130"
    state: started
    restart_policy: always
    command: "dev -conf okapi/okapi.json"
    restart: yes
