---
# Install openjdk-8-jdk
- name: Install python-apt/openjdk-8-jdk
  become: yes
  apt:
    name:
      - python3-apt
      - openjdk-8-jdk

- name: Make Java 8 the system default
  become: yes
  shell: update-java-alternatives --set java-1.8.0-openjdk-amd64 && touch /etc/.set_javadefault_ansible
  args:
    creates: /etc/.set_javadefault_ansible
