---
# defaults
okapi_port: 9130
okapi_url: "http://{{ ansible_default_ipv4.address }}:{{ okapi_port }}"
folio_cron_branch: master
tenant: diku
admin_user:
  username: diku_admin
  password: admin
# Optional, will default to config from folioCronService package
# config_dir: folio_cron_jobs # Optional, default to "folio_cron_jobs" in Ansible user's directory
# folio_cron_jobs:
#   - name: scheduled-age-to-lost-fee-charging
#     user_config_section: DEFAULT # Optional, default "DEFAULT"
#     cron_time: "*/30 * * * *"
#     tenant: diku # Optional, default "{{ tenant }}"
#     api_path: "/circulation/scheduled-age-to-lost-fee-charging"
#     method: POST
#     data: # Optional, default to empty object
#       active: "true" # note quoted value, these are query params
