---
# pg_admin credentials should be for a superuser
pg_admin_user: folio_admin
pg_admin_password: folio_admin
pg_host: "{{ ansible_default_ipv4.address }}"
pg_port: 5432
pg_maint_db: postgres
db_admin_user: folio_module_admin
db_admin_password: folio_module_admin
db_encoding: UTF-8
db_lc_collate: und-x-icu
db_lc_ctype: und-x-icu
db_template: template0
database_name: okapi_modules
folio_install_type: single_server
rds: false
